### ISSUE TITLE
Can't get a bot to work

### ISSUE THREAD

**Issue by JammyWaffles** [bwmarrin/discordgo#581] opened 2018-08-31 17:19 UTC
I've followed all the steps but can enter the command for the bot name and token, the .exe just gives me errors, I'm not sure what to do or where to go from here, please help.
![blerp](https://user-images.githubusercontent.com/19975472/44926738-59c3f600-ad4a-11e8-91ee-5754f2f92f23.png)

**Comment by Zyian** [comment] 2018-09-04 13:15
Without some code, it's would be hard to pin point where the issue is coming from, if I had to guess, are you closing the connection from session.Open()?

**Comment by bwmarrin** [comment] 2018-09-06 02:56
The errors look like it's in some weird loop constantly calling Close().  Have you tried just using the pingpong example, unmodified, with your bot token? See if that works.
https://github.com/bwmarrin/discordgo/tree/master/examples/pingpong


For us to debug this any further, as @Zyian mentioned, we're going to need to see your code.

**Comment by bwmarrin** [comment] 2018-09-18 21:28
@JammyWaffles any update or progress on this?

**Comment by JammyWaffles** [comment] 2018-09-18 22:50
> @JammyWaffles any update or progress on this?

I tried but nothing seemed to work so I just gave up on that one and moved onto another, but thanks for the help.

**Comment by bwmarrin** [comment] 2018-09-19 15:05
Well, I would be happy to help if you could give more details or hop into the Discord Gopher's chat server and we could discuss it. I'm sure we can get you going.

However, I'll close out this ticket for now as it seems you've moved on.  Feel free to reopen it or join chat if you'd like to revisit getting your Go bot working.

**Closed by bwmarrin** 2018-09-19 15:05 UTC
