### ISSUE TITLE
i can't receive sound from discord

### ISSUE THREAD

**Issue by kinoher** [bwmarrin/discordgo#598] opened 2018-10-12 17:33 UTC
problem commits c8554477e44900990a8fbad29ca17ecb3412e832 73f6772a2b7cc95e29c462e4f15bf07cbe0d3854

problem: hello i can't receive sound from discord because data from channel  don't arrive. 
my code for test https://gist.github.com/kinoher/fb9da8545a5db2ab342ebd524163c849
it's very dirty code i cuted from another my service

**Comment by robbix1206** [comment] 2018-10-12 22:09
Be more clear with 

> problem commits

When i saw that for the first time i was thinking that you were accusating this commits to be the origin of this bug. (Use something like commit where I was able to reproduce the bug)
I've tested the voice reception with master and develop branch without any problem.
Try your voice reception with https://gist.github.com/robbix1206/0d24c8e33956f5b307de607ab1e3d376.
If it correctly display something on your terminal, that indicate that your correctly receive packets from discordgo, so the problem may come from somewhere else.

**Comment by mortdeus** [comment] 2018-11-02 12:20
i can also confirm i have this issue with a bot with admin permissions. I can get it to join the voice channel but whenever it comes to receiving on the Recv Opus channel it just hangs.

**Comment by robbix1206** [comment] 2018-11-02 13:50
First of all check if your bot join without deafen set to true.
Also did you tried my gist ? (It is checking that you are correctly receiving audio data)
If my gist work for you, you should assume that the problem doesn't come from discordgo.
Are you using something after receiving audio that can block because of something else ?

**Comment by mortdeus** [comment] 2018-11-02 19:40
What i am curious is whether the link you posted works for you? As in you can record spoken audio from a discord channel where a bot is in with admin permissions and both input and output channels unmuted, save it locally, and replay it in another application?

**Comment by mortdeus** [comment] 2018-11-02 19:45
looking at the code itself, there are opcodes that discordgo doesn't even address. Also other libraries like discord.py no longer handle voice connections correctly. 

And when you read the documentation at [voice connections](https://discordapp.com/developers/docs/topics/voice-connections)
there is a section 

> The plain mode is no longer supported. All data should be sent using a supported encryption method, right now only xsalsa20_poly1305.

That doesn't appear to be addressed in discordgo. From my testing, it appears that the issue stems from proper udp init, as i am getting all the websocket responses like normal.

**Comment by bwmarrin** [comment] 2018-11-02 20:55
Which opcodes @mortdeus ?

For the encryption comment, DiscordGo has had that for quite a while now.

@robbix1206 comment specifically states that it was tested on both master and develop and worked on both.  

Not sure what the discord.py part is about :) But, I do know Discord  changes the API a lot so it can be difficult for some libraries to keep things up to date.

Can you post your code (as gist, or a link to a repo), or an example that demonstrates the problem @mortdeus ? Doing that might make it easier for someone to see what's causing the issue for you.

**Comment by waynegerard** [comment] 2018-12-07 22:19
Hey there! Not sure if this ever got resolved, but I'm actually having similar troubles. I couldn't even get the simple code to work (https://gist.github.com/robbix1206/0d24c8e33956f5b307de607ab1e3d376). 

Adding some debug logs in, it seems like everything's being setup correctly. The UDP connection gets established, but the only packets I'm receiving look like simple sequence packets (they're also only 8 bytes long).

I don't think it's a permission issue, as I gave the bot blanket permissions on our test server. It's also receiving voice status updates, so it's receiving information about when I start/stop speaking just not the actual voice data itself (though I realize that seems to come in through the ws and not through UDP). 

I'll keep poking around, but just wanted to add a small data point. I'm on 1.11.2 if that makes any difference.

**Comment by Bios-Marcel** [comment] 2019-02-19 09:58
Any news on this? I'd love to see this resolved. If not, could give any hints on how to resolve this?

**Comment by Hinara** [comment] 2019-02-19 17:38
Just a quick comment to tell that the example code is there https://gist.github.com/Hinara/0d24c8e33956f5b307de607ab1e3d376
It's just that I've changed of username on github (which make old links to the gist invalid)

**Comment by Bios-Marcel** [comment] 2019-02-19 18:36
I'll be testing this again and record it

**Comment by Bios-Marcel** [comment] 2019-02-19 21:00
Here, I have tested your example code, it doesn't receive any opus packets.

Here is ya wireshark capture. Receiving the data worked for sure, it's just that discordgo doesn't notice.
[voicecapture.pcapng.gz](https://github.com/bwmarrin/discordgo/files/2881955/voicecapture.pcapng.gz)

**Comment by Hinara** [comment] 2019-02-19 23:56
Doesn't seem to be a trouble with the firewall as packets flow normally in both directions :/

**Comment by Bios-Marcel** [comment] 2019-02-20 06:28
Yeah, I think so too. I also tested it with different laptops and machiney, both running linux tho.

**Comment by Bios-Marcel** [comment] 2019-02-20 22:49
Some things I found out:

* The UDP connection constantly receives packages simply counting up from 0, the rest of the data is always `0x00`
* We seem to be using the default API, meaning version `v1`, but `v3` is the latest (Maybe I am missunderstanding this?) https://discordapp.com/developers/docs/topics/voice-connections#voice-gateway-versioning

**Comment by Bios-Marcel** [comment] 2019-02-23 14:48
So, someone found out that you start receiving data after sending a "silent packet"

```go
connection.OpusSend <- []byte{0xf8, 0xff, 0xfe}
```

**Comment by kinoher** [comment] 2019-04-26 20:42
@Bios-Marcel  please proof. I try sending "silent packet" but i don't start receiving sound

**Comment by Bios-Marcel** [comment] 2019-04-26 20:46
Sorry @kinoher, it seems that my voice implementation isnt really working anymore and I currently don't want to debug that stuff.

**Comment by yuko1225** [comment] 2019-06-25 02:22
Have same issue here. Demo code from @Hinara isn't printing anything. Tcpdump shows it does receive UDP packets from discord but nothing printed out. No NAT and no firewall.

Solution from @Bios-Marcel doesn't work either.

**Comment by yuko1225** [comment] 2019-06-25 08:53
Okay I found the cause of this issue after I look a bit closer.

It's actually has something to do with wrong NAT implementation in discordgo. Tcpdump shows that discord server is trying to send the actual sound data to a port that discordgo isn't really listening. While I can't pinpoint which code cause this behavior yet, I can tell a temporary solution: put the bot behind NAT. Yes instead put the bot on a open internet, put it behind NAT actually solve this. At least in my case.

**Comment by Bios-Marcel** [comment] 2019-07-22 17:38
Can this be closed?

**Closed** 2019-07-30 21:46 UTC
