### ISSUE TITLE
Voice connections not receiving data

### ISSUE THREAD

**Issue by tystuyfzand** [bwmarrin/discordgo#423] opened 2017-08-13 19:45 UTC
After some trial and error, I noticed that the header type is now 0x90 for some reason... This issue pretty much sums it up: https://github.com/hammerandchisel/discord-api-docs/issues/231

This is from the official desktop client too, so there's something going on here. For now, the simplest fix is to allow 0x90 alongside 0x80, and skip 8 bytes off p.Opus if the type is 0x90. If there's no better idea, I'll submit a PR if someone would like to confirm this issue.

**Comment by robbix1206** [comment] 2017-09-21 18:27
As said in the referenced issue this is not a bug from the library but from senders, so I'm not sure that we need to implement a fix for that as
>If there's any malformed data in third party libraries you should open issues on their respective bug trackers.

**Comment by jonas747** [comment] 2017-09-25 13:20
This was fixed in https://github.com/bwmarrin/discordgo/commit/3c8a0dd940b7ca98488d829131d9cf14cb838766

**Closed** 2017-12-25 19:01 UTC
