### ISSUE TITLE
Panic on session.ChannelVoiceJoin in deafened=false mode

### ISSUE THREAD

**Issue by la4zen** [bwmarrin/discordgo#1172] opened 2022-04-28 12:33 UTC
```go
// (ss *discordgo.Session, m *discordgo.MessageCreate)
if strings.HasPrefix(m.Content, "..join") {
	c, err := ss.State.Channel(m.ChannelID)
	if err != nil {
		return
	}
	g, err := ss.State.Guild(c.GuildID)
	if err != nil {
		return
	}
	for _, vs := range g.VoiceStates {
		if vs.UserID == m.Author.ID {
			vc, err := ss.ChannelVoiceJoin(c.GuildID, vs.ChannelID, true, false)
			if err != nil {
				return
			}
			print(vc)
			return
		}
	}
}
```
This code throws
```
panic: slice bounds out of range [:4] with capacity 0
github.com/bwmarrin/discordgo.(*VoiceConnection).opusReceiver(0xc00039d4a0, 0xc00009a3d0, 0xc000280900, 0xc0000f6960)
        go/pkg/mod/github.com/bwmarrin/discordgo@v0.25.0/voice.go:837 +0x575
created by github.com/bwmarrin/discordgo.(*VoiceConnection).onEvent
        go/pkg/mod/github.com/bwmarrin/discordgo@v0.25.0/voice.go:441 +0x573
```

**Comment by FedorLap2006** [comment] 2022-04-28 13:42
Duplicate of #1161

**Closed by FedorLap2006** 2022-04-28 13:42 UTC
